// Micro-training modules for bystanders. IDs are shared with the AI service's video catalog so the
// chatbot can recommend a module. Videos are official British Red Cross / St John Ambulance clips.
// Guidance follows standard lay-responder first aid; it supports, and never replaces, calling for help.

export const TRAINING = [
  {
    id: 'cpr',
    title: 'CPR — not breathing',
    category: 'Life-saving',
    minutes: 3,
    color: '#ef4444',
    youtubeId: 'gDmy0of0XAk',
    source: 'British Red Cross',
    summary: 'Unresponsive and not breathing normally? Push hard and fast in the centre of the chest.',
    steps: [
      { title: 'Check for danger & response', body: 'Make sure the area is safe. Shout and gently shake their shoulders.' },
      { title: 'Call for help', body: 'Call the emergency number on speaker, or get someone else to. Ask for a defibrillator (AED).' },
      { title: 'Check breathing', body: 'Tilt the head back, lift the chin and look for normal breathing for up to 10 seconds.' },
      { title: 'Start compressions', body: 'Heel of one hand in the centre of the chest, other hand on top. Push down 5–6 cm, 100–120 times a minute.' },
      { title: "Don't stop", body: 'Keep going until help arrives, an AED tells you to stop, or they start breathing normally.' },
    ],
    metronome: true,
  },
  {
    id: 'bleeding',
    title: 'Severe bleeding',
    category: 'Life-saving',
    minutes: 2,
    color: '#dc2626',
    youtubeId: 'NxO5LvgqZe0',
    source: 'St John Ambulance',
    summary: 'Apply firm, continuous pressure to the wound to stop the blood loss.',
    steps: [
      { title: 'Apply pressure', body: 'Press firmly on the wound with a clean cloth or pad. Use your hand if nothing else is available.' },
      { title: 'Call for help', body: 'Call the emergency number. Keep pressing while you talk.' },
      { title: 'Keep pressing', body: 'Do not lift to check. If blood soaks through, add more pads on top and press harder.' },
      { title: 'Treat for shock', body: 'Lay them down, raise their legs if possible, and keep them warm and calm.' },
    ],
  },
  {
    id: 'choking',
    title: 'Choking adult',
    category: 'Life-saving',
    minutes: 2,
    color: '#ca8a04',
    youtubeId: '6E9AXXRdkfE',
    source: 'British Red Cross',
    summary: 'If they cannot cough, speak or breathe: back blows, then abdominal thrusts.',
    steps: [
      { title: 'Encourage coughing', body: 'If they can cough, tell them to keep coughing to clear the blockage.' },
      { title: '5 back blows', body: 'Lean them forward and give up to 5 sharp blows between the shoulder blades with the heel of your hand.' },
      { title: '5 abdominal thrusts', body: 'Stand behind, fist above the belly button, pull sharply inwards and upwards up to 5 times.' },
      { title: 'Repeat & call', body: 'Alternate back blows and thrusts. Call the emergency number if it has not cleared.' },
    ],
  },
  {
    id: 'burns',
    title: 'Burns & scalds',
    category: 'Injury',
    minutes: 2,
    color: '#f97316',
    youtubeId: 'dQozahCH8IE',
    source: 'British Red Cross',
    summary: 'Cool the burn under cold running water for at least 20 minutes.',
    steps: [
      { title: 'Cool it', body: 'Hold the burn under cool running water for at least 20 minutes. No ice, butter or creams.' },
      { title: 'Remove jewellery', body: 'Gently remove rings or tight items near the burn before it swells — unless stuck to the skin.' },
      { title: 'Cover loosely', body: 'Cover with cling film or a clean plastic bag once cooled.' },
      { title: 'Get help', body: 'Call for help for large, deep, facial or electrical burns, or burns on children.' },
    ],
  },
  {
    id: 'recovery_position',
    title: 'Recovery position',
    category: 'Life-saving',
    minutes: 2,
    color: '#3b82f6',
    youtubeId: '5fK2oCiz8VU',
    source: 'British Red Cross',
    summary: 'Unresponsive but breathing? Roll them onto their side to keep the airway open.',
    steps: [
      { title: 'Check breathing', body: 'Confirm they are unresponsive but breathing normally.' },
      { title: 'Roll onto side', body: 'Place the near arm at a right angle, bring the far hand to their cheek, bend the far knee and roll them towards you.' },
      { title: 'Open airway', body: 'Tilt the head back slightly so their airway stays open and fluids can drain.' },
      { title: 'Monitor', body: 'Call the emergency number and keep checking their breathing until help arrives.' },
    ],
  },
  {
    id: 'fracture',
    title: 'Broken bones',
    category: 'Injury',
    minutes: 2,
    color: '#8b5cf6',
    youtubeId: 'CP-vb0xxzFM',
    source: 'British Red Cross',
    summary: 'Support the injury so it does not move, and get medical help.',
    steps: [
      { title: "Don't move it", body: 'Encourage them to keep the injured part still. Do not try to straighten it.' },
      { title: 'Support it', body: 'Use a rolled towel, clothing or cushions to support the injury in the position found.' },
      { title: 'Get help', body: 'Call the emergency number for suspected neck, back, hip or thigh injuries or open wounds.' },
    ],
  },
  {
    id: 'seizure',
    title: 'Seizures',
    category: 'Medical',
    minutes: 2,
    color: '#0ea5e9',
    youtubeId: '1SMFUwyEafw',
    source: 'British Red Cross',
    summary: 'Protect them from injury and time the seizure. Never restrain them.',
    steps: [
      { title: 'Protect', body: 'Move hard or sharp objects away. Cushion their head. Do not hold them down or put anything in their mouth.' },
      { title: 'Time it', body: 'Note when it started. Call for help if it lasts more than 5 minutes or is their first seizure.' },
      { title: 'Recovery position', body: 'When the jerking stops, put them in the recovery position and stay with them.' },
    ],
  },
  {
    id: 'heatstroke',
    title: 'Heat exhaustion',
    category: 'Environmental',
    minutes: 2,
    color: '#ea580c',
    youtubeId: 'W-Us9IP33Gs',
    source: 'British Red Cross',
    summary: 'Move them somewhere cool, give water, and cool the skin.',
    steps: [
      { title: 'Move to shade', body: 'Get them to a cool place and help them lie down with legs raised.' },
      { title: 'Rehydrate', body: 'Give plenty of water or an oral rehydration drink if they are alert.' },
      { title: 'Cool them', body: 'Sponge or spray them with cool water and fan them.' },
      { title: 'Watch for heatstroke', body: 'Confusion, no sweating or collapse is an emergency — call for help immediately.' },
    ],
  },
];

export const getTraining = (id) => TRAINING.find((t) => t.id === id);
